In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('spam.csv')

In [7]:
df.sample(5)

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
886,ham,I like to talk pa but am not able to. I dont k...,NaN,NaN,NaN
2241,ham,U buy newspapers already?,NaN,NaN,NaN
3875,ham,did u get that message,NaN,NaN,NaN
2364,ham,Ok then no need to tell me anything i am going...,NaN,NaN,NaN
5322,ham,"Thanks, I'll keep that in mind",NaN,NaN,NaN

In [9]:
df.shape

(5572, 5)

In [10]:

# data cleaning
# EDA
# Text processing
# Model bulding
# Evaluation
# Improvements

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB

In [12]:
df.drop(columns=['Unnamed: 2','Unnamed: 3','Unnamed: 4'])

        v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will �_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [ ]:
df.rename(columns={'v1':'Target','v2':'Text'})